config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get '/random' => 'pages#random'
  get '/search' => 'pages#search'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def get_photos(user_id)
    flickr.photos.search(user_id: user_id)
  end

  # get url from photos and group photo urls in twos for
  # easy display & processing
  def parse_photos(photos)
    photos.map do |photo|
      FlickRaw.url_b(photo)
    end.in_groups_of(2)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def search
    begin
      photos = get_photos(user_id[:search_user_id])
      @photos_urls = parse_photos(photos)
      render 'index'
    rescue
      flash.now[:notice] = "No such user_id in flickr database :("
      render 'index'
    end
  end

  def random
    @photos_urls = parse_photos(flickr.photos.getRecent)
    render 'index'
  end

  private

  def user_id
    params.require(:search).permit(:search_user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FlickrApi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/_photos.html.erb
<style>
  .flickr ul
  {
    list-style-type: none;
    margin: 0;
    padding: 0;
  }
  .flickr ul li
  {
    border-bottom: 0;
    margin: 0;
    padding: 0;
  }

  .flickr_photo
  {
    width: 75px;
    height: 75px;
    padding: 12px 10px 32px 13px;
    margin: 0;
  }
</style>


<div class="flickr">
  <ul>
    <% @photos_urls.each do |row| -%>
        <li>
          <% row.each do |photo_url| %>
              <%= link_to(image_tag(photo_url, class: 'flickr_photo', :border => 0, :size => '75x75'), photo_url, target: '_blank') unless photo_url.nil? %>
          <% end %>
        </li>
    <% end -%>
  </ul>
</div>

app/views/pages/index.html.erb
<h1>Pictures index</h1>
<p style="color: green; border: 1px black;"><%= flash[:notice] %></p>
<%= form_for :search, url: search_path, method: 'get' do |f| %>
  <%= f.text_field :search_user_id, placeholder: '140117433@N04' %>
  <%= f.submit "Search" %>
<% end %>
<p>
  Don't know who to search for?
  <%= form_for :random, url: random_path, method: 'get' do |f| %>
    <% f.submit "Random" %>
  <% end %>
</p>
<%= debug(params) if Rails.env.development? %>
<% if @photos_urls.nil? %>
    <p> No photos found lets search for some!</p>
<% else %>
  <%= render 'photos' %>
<% end %>